receivers:
  otlp:
    protocols:
      grpc:
  loki:
    protocols:
      http:
        endpoint: :3500
    use_incoming_timestamp: true

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: ${env:TRACES_URL}
    tls:
      insecure: false
    auth:
      authenticator: basicauth/traces

  prometheusremotewrite:
    endpoint: ${env:METRICS_URL}
    auth:
      authenticator: basicauth/metrics

  loki:
    endpoint: ${env:LOGS_URL}
    auth:
      authenticator: basicauth/logs

processors:
  spanmetrics:
    metrics_exporter: prometheusremotewrite
  attributes:
    actions:
      - action: insert
        key: loki.format
        value: raw
      - action: insert 
        key: loki.attribute.labels 
        value: service_name

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  basicauth/traces:
    client_auth:
      username: "${env:TRACES_USER_ID}"
      password: "${env:TRACES_API_KEY}"
  basicauth/metrics:
    client_auth:
      username: "${env:METRICS_USER_ID}"
      password: "${env:METRICS_API_KEY}"
  basicauth/logs:
    client_auth:
      username: "${env:LOGS_USER_ID}"
      password: "${env:LOGS_API_KEY}"   

connectors:
  spanmetrics:

service:
  extensions: [ basicauth/traces, basicauth/metrics, basicauth/logs, health_check ]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [otlp, spanmetrics]
    logs:
      receivers: [loki]
      processors: [attributes]
      exporters: [loki]
  telemetry:
    logs:
      level: "debug"